theme: minima
title: My Website
author: Ohm Patel
email: Oapatel@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  This is my website for AP Computer Science A

# social links
github_username:  Oapatel2303 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
